/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoGUI;

import Crud.Reporte;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectomesas.Cliente;

/**
 *
 * @author Hector
 */
public class VentanaVentas extends javax.swing.JDialog {
    int modo;
    /**
     * Creates new form VentanaVentas
     */
    public VentanaVentas(java.awt.Frame parent, boolean modal,int modo) {
        super(parent, modal);
        initComponents();
        this.modo=modo;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDFecha1 = new com.toedter.calendar.JDateChooser();
        jDFecha2 = new com.toedter.calendar.JDateChooser();
        jLResultado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 64, 165, -1));
        getContentPane().add(jDFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 121, 165, -1));

        jLResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLResultado.setForeground(new java.awt.Color(255, 255, 255));
        jLResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 230, 61));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Desde: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 44, 165, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Hasta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 98, -1, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 64, 75, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 118, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoR.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (this.jDFecha1.getDate()!=null && this.jDFecha2.getDate()!=null)
        {
            if (modo==1)
            {
                this.generarReporte();
            }
            
            if (modo==2)
            {
                VentanaTabla ventana =  new VentanaTabla(null,true);
                ventana.setTabla(this.generarTabla());
                ventana.setVisible(true);
            }
            
            if (modo==3)
            {
                VentanaTabla ventana =  new VentanaTabla(null,true);
                ventana.setTabla(this.generarTablaTop());
                ventana.setVisible(true);
            }
            
            if (modo==4)
            {
                VentanaTabla ventana =  new VentanaTabla(null,true);
                ventana.setTabla(this.generarTablaClientes());
                ventana.setVisible(true);
            }
            
            if (modo==5)
            {
                VentanaTabla ventana =  new VentanaTabla(null,true);
                ventana.setTabla(this.generarTablaComprasClientes());
                ventana.setVisible(true);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Debe Ingresar una fecha");
        }
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void generarReporte()
    {
        Reporte reporte = new Reporte();
        Date fecha1 = new java.sql.Date(this.jDFecha1.getDate().getTime());
        Date fecha2 = new java.sql.Date(this.jDFecha2.getDate().getTime());
        
        int resultado = reporte.consultarVentasTotales(fecha1, fecha2);
        this.jLResultado.setText("Ventas Totales: "+resultado+"");
    }
    
    public DefaultTableModel generarTabla()
    {
        Date fecha1 = new java.sql.Date(this.jDFecha1.getDate().getTime());
        Date fecha2 = new java.sql.Date(this.jDFecha2.getDate().getTime());
        DefaultTableModel modelo;
        String titulo[]={" Numero Mesa "," Ventas "};
        Reporte controlador = new Reporte();
        ArrayList<String[]> res = controlador.consultarVentasMesas(fecha1,fecha2);
        String [][] tabla = new String[res.size()][2];
        for (int i = 0; i < res.size(); i++)
        {
            String[] datos=res.get(i);
            tabla[i]=datos; 
        }
        modelo=new DefaultTableModel(tabla,titulo);
        return modelo;
    }
    
    public DefaultTableModel generarTablaTop()
    {
        Date fecha1 = new java.sql.Date(this.jDFecha1.getDate().getTime());
        Date fecha2 = new java.sql.Date(this.jDFecha2.getDate().getTime());
        DefaultTableModel modelo;
        String titulo[]={" Cantidad Ventas"," Nombre "};
        Reporte controlador = new Reporte();
        ArrayList<String[]> res = controlador.consultarTop(fecha1,fecha2);
        String [][] tabla = new String[res.size()][2];
        for (int i = 0; i < res.size(); i++)
        {
            String[] datos=res.get(i);
            tabla[i]=datos; 
        }
        modelo=new DefaultTableModel(tabla,titulo);
        return modelo;
    }
    
    public DefaultTableModel generarTablaClientes()
    {
        Date fecha1 = new java.sql.Date(this.jDFecha1.getDate().getTime());
        Date fecha2 = new java.sql.Date(this.jDFecha2.getDate().getTime());
        DefaultTableModel modelo;
        String titulo[]={" Cedula"," Nombre Completo "," Telefono "};
        Reporte controlador = new Reporte();
        ArrayList<Cliente> res = controlador.consultarClientesAusentes(fecha1,fecha2);
        String [][] tabla = new String[res.size()][3];
        for (int i = 0; i < res.size(); i++)
        {
            String[] datos = res.get(i).consultarInformación();
            tabla[i]=datos; 
        }
        modelo=new DefaultTableModel(tabla,titulo);
        return modelo;
    }
    
    public DefaultTableModel generarTablaComprasClientes()
    {
        Date fecha1 = new java.sql.Date(this.jDFecha1.getDate().getTime());
        Date fecha2 = new java.sql.Date(this.jDFecha2.getDate().getTime());
        DefaultTableModel modelo;
        String titulo[]={" Cedula"," Nombre Completo "," Precio "};
        Reporte controlador = new Reporte();
        ArrayList<String[]> res = controlador.consultarComprasClientes(fecha1,fecha2);
        String [][] tabla = new String[res.size()][3];
        for (int i = 0; i < res.size(); i++)
        {
            String[] datos=res.get(i);
            tabla[i]=datos; 
        }
        modelo=new DefaultTableModel(tabla,titulo);
        return modelo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDFecha1;
    private com.toedter.calendar.JDateChooser jDFecha2;
    private javax.swing.JLabel jLResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
