/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoGUI;

import javax.swing.JOptionPane;
import proyectomesas.Administrador;
import Crud.CrudAdministrador;
import Crud.CrudMesero;
import proyectomesas.Mesero;

/**
 *
 * @author Hector
 */
public class VentanaLogin extends javax.swing.JFrame {

    private String correo;
    private String contraseña;
    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngreso = new javax.swing.JButton();
        jtxCorreo = new javax.swing.JTextField();
        jtxContrasena = new javax.swing.JPasswordField();
        jLMensaje2 = new javax.swing.JLabel();
        jLMensaje1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngreso.setText("Ingresar");
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jtxCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(jtxCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 79, 192, -1));
        getContentPane().add(jtxContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 192, -1));

        jLMensaje2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLMensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 105, 192, 9));

        jLMensaje1.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 151, 192, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoR.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxCorreoActionPerformed

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        this.correo=jtxCorreo.getText();
        this.contraseña=jtxContrasena.getText();

        CrudMesero mesero = new CrudMesero(null);
        Mesero meseroLogin = mesero.consultarLogin(correo);
        if (meseroLogin!=null)
        {
            if (meseroLogin.getContraseña().equals(contraseña))
            {
                jLMensaje1.setText("");
                jLMensaje2.setText("");
                jtxContrasena.setText("");
                PrincipalMesero ventana = new PrincipalMesero(this,true,meseroLogin);
                ventana.setVisible(true);
            }
            else
            {
                jLMensaje2.setText("");
                jLMensaje1.setText("Contraseña Invalida");
            }
        }
        else
        {
            CrudAdministrador controlador = new CrudAdministrador(null);
            Administrador admin = controlador.consultarLogin(correo);

            if (admin!=null) 
            {
                if (admin.getContraseña().equals(contraseña))
                {   
                    jLMensaje1.setText("");
                    jLMensaje2.setText("");
                    jtxContrasena.setText("");
                    PrincipalAdmin ventanaAdmin = new PrincipalAdmin(this, true);
                    ventanaAdmin.setVisible(true);
                }
                else
                {
                    jLMensaje2.setText("");
                    jLMensaje1.setText("Contraseña Invalida");
                }
            }
            else
            {
                jLMensaje1.setText("");
                jLMensaje2.setText("Usuario NO encontrado");
            }
        }  
    }//GEN-LAST:event_btnIngresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngreso;
    private javax.swing.JLabel jLMensaje1;
    private javax.swing.JLabel jLMensaje2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jtxContrasena;
    private javax.swing.JTextField jtxCorreo;
    // End of variables declaration//GEN-END:variables
}
