/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoGUI;

import Crud.CrudMesero;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import Crud.CrudProducto;
import Crud.CrudTipo;
import javax.swing.JOptionPane;
import proyectomesas.Mesero;
import proyectomesas.Producto;
import proyectomesas.Tipo;

/**
 *
 * @author Hector
 */
public class VentanaAgregarProducto extends javax.swing.JDialog implements ActionListener,AdjustmentListener{

    JScrollPane scroll;
    JPanel panel;
    Producto producto;
    int pos=10;
    int pos2=10;
    ArrayList<JButton> b;
    ArrayList<Producto> productos;
    /**
     * Creates new form VentanaAgregarProducto
     */
    public VentanaAgregarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        b= new ArrayList<>();
        this.pintarProductos();
        this.setLayout(null);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void pintarProductos()
    {        
       producto = new Producto("", "", 0, "", "");
       CrudProducto productoCrud = new CrudProducto(producto);
       productos = productoCrud.consultarTodos();

        Container c = this.getContentPane();
        panel = new JPanel();
        //panel.setBackground(Color.yellow);
        panel.setLocation(0, 0);
        panel.setLayout(null);
        panel.setSize(this.getWidth(), this.getHeight());
        
        for (int i = 0; i < productos.size(); i++) 
        {
            Producto p = productos.get(i);
            JPanel panel1 = new JPanel();
            //panel1.setBackground(Color.red);
            panel1.setSize(this.getWidth()-140,100);
            panel1.setLocation(10, pos2);
            pos2=110+pos2;
            panel1.setLayout(null);
            
            String nombrebtn = i+1+"";
            String descripcion = p.getDescripcion();
            String inf = "<html>Nombre: "+p.getNombre()+"<br>" + "Precio: "+p.getPrecio() +"<br>"+ "Descripcion: "+ this.descripcion(descripcion)+"<html>";

            
            JButton b =new JButton();
            b.setName("Seleccionar");
            b.setLocation(0, 0);
            b.setSize((this.getWidth()-140)/2,100);
            b.addActionListener(this);
            b.setBackground(Color.cyan);
            b.setLayout(null);
            b.setText(inf);
            b.setFocusable(false);
            b.setHorizontalAlignment(SwingConstants.LEFT);
            
            ImageIcon imagen = new ImageIcon("src/imagenes/2.jpg");
            JLabel label = new JLabel();
            label.setIcon(imagen);
            label.setBounds(160,0,(this.getWidth()-140)/2,100);
            System.out.println((this.getWidth()-140)/2);
            panel1.add(label);

            this.b.add(b);

            panel1.add(b);
            panel.add(panel1);
        }
        
        JButton aceptar =new JButton();
        aceptar.setName("Agregar");
        aceptar.setText("Agregar");
        aceptar.setSize(100, 30);
        

        panel.setPreferredSize(new Dimension(this.getWidth(), 10+productos.size()*110));
        aceptar.setLocation((this.getWidth())-aceptar.getWidth()+5,10);
        aceptar.setFocusable(false);
        aceptar.addActionListener(this);
        b.add(aceptar);
        c.add(aceptar);
         
        
        scroll = new JScrollPane(panel,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setSize(this.getWidth()-100, this.getHeight());
        this.setSize(scroll.getWidth()+aceptar.getWidth()+30,scroll.getHeight()+30);
        scroll.setLocation(0, 0);
        JScrollBar p = scroll.getVerticalScrollBar();
        p.addAdjustmentListener(this);
        c.add(scroll);
        this.repaint();
    }
    
    public String descripcion(String inf)
    {
        String res=inf;
        if (inf.length()>10)
        {
            res = inf.subSequence(0, 7)+"...";
        }
        return res;
    }

    @Override
    public void actionPerformed(ActionEvent e) 
    {
        CrudTipo controlador = new CrudTipo(null);
        Producto p2=null;
        ArrayList<Tipo> tipos = controlador.consultarTodos();
        for (int i = 0; i < b.size(); i++)
        {
            if (e.getSource() == b.get(i) && b.get(i).getName().equals("Agregar")) 
            {
               VentanaAgregar ventana = new VentanaAgregar(null, true);
               ventana.iniciar();
               ventana.SetTipo(tipos);
               ventana.setVisible(true);
               boolean estado = ventana.isPulsador();
               if (estado)
               {
                   Producto p = new Producto(ventana.getjTId(), ventana.getjTNombre()
                                            ,Float.parseFloat(ventana.getjTPrecio()),
                                            ventana.getjTDescripcion(),ventana.buscarSeleccion());
                   CrudProducto controlador2 = new CrudProducto(p);
                   int control = controlador2.insertar();
                   if (control==1)
                   {
                       JOptionPane.showMessageDialog(this, "Se agrego un producto");
                   }
               }
            }
            else
            {
                if (e.getSource() == b.get(i) && b.get(i).getName().equals("Seleccionar"))
                {
                    p2 = productos.get(i);
                    int seleccion = this.mostrarOpciones();
                    this.verificarSeleccion(seleccion,p2);
                }
            }
        }
    }

    @Override
    public void adjustmentValueChanged(AdjustmentEvent ae) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
        
     public int mostrarOpciones()
    {
        int seleccion = JOptionPane.showOptionDialog( null,"Seleccione una opcion",
                     "Selector de opciones",JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE,null,
                    new Object[] { "Eliminar", "Modificar"},"opcion 1");
        
        return seleccion;
    }
    
    public void  removerProducto(Producto p)
    {
        CrudProducto controlador = new CrudProducto(null);
        controlador.eliminar(p.getId());
    }
    
    public void modificarMesero(Producto p)
    {
        VentanaAgregar ventana = new VentanaAgregar(null, true);
        ventana.iniciar();
        ventana.setjId(p.getId());
        ventana.setjTNombre(p.getNombre());
        ventana.ocultarId();
        ventana.setjTPrecio(p.getPrecio()+"");
        ventana.setjTDescripcion(p.getDescripcion());
        ventana.ocultarTipo();
        ventana.setVisible(true);
        
        boolean pulsado = ventana.isPulsador();
        
        if(pulsado)
        {
            p.setNombre(ventana.getjTNombre());
            p.setPrecio(Float.parseFloat(ventana.getjTPrecio()));
            p.setDescripcion(ventana.getjTDescripcion());
            
            CrudProducto controlador = new CrudProducto(p);
            int i = controlador.modificar();
            
            if(i == 1)
            {
                JOptionPane.showMessageDialog(this, "Producto modificado");
            }else
            {
                JOptionPane.showMessageDialog(this, "No se pudo modificar el producto");
            }
        }
    }
    
    public void verificarSeleccion(int seleccion,Producto p)
    {
        if (seleccion==0)
        {
            this.removerProducto(p);
            JOptionPane.showMessageDialog(this, "Producto eliminado");
        }
        else
        {
            if (seleccion==1)
            {
                this.modificarMesero(p);
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
