/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoGUI;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import Crud.CrudMesero;
import proyectomesas.Mesero;

/**
 *
 * @author Hector
 */
public class VentanaAgregarMesero extends javax.swing.JDialog {
    boolean pulsador;
    /**
     * Creates new form VentanaAgregarMesero
     */
    public VentanaAgregarMesero(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //initComponents();
        this.pulsador = false;
        this.setLayout(null);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    public void setContraseña(String contraseña)
    {
        this.jContraseña.setText(contraseña);
    }
    
    public void ocultarContraseña()
    {
        this.jContraseña.setEditable(false);
    }
    
    public void setNombres(String nombres)
    {
        this.jTNombres.setText(nombres);
    }
    
    public void setApellidos(String apellidos)
    {
        this.jTApellidos.setText(apellidos);
    }
    
    public void setTelefono(String telefono)
    {
        this.jTTelefono.setText(telefono);
    }
    
    public void setCorreo(String correo)
    {
        this.jTCorreo.setText(correo);
    }
    
    public void ocultarCorreo()
    {
        this.jTCorreo.setEditable(false);
    }
    
    public void setCedula(String cedula)
    {
        this.jTCedula.setText(cedula);
    }
    
    public void setDireccion(String direccion)
    {
        this.jTDireccion.setText(direccion);
    }
    
    public void setObservaciones(String observaciones)
    {
        this.jTObservaciones.setText(observaciones);
    }
    
    public void iniciar()
    {
        this.initComponents();
    }
    
    public void ocultarCedula()
    {
        this.jTCedula.setEditable(false);
    }

    public String getjTApellidos() {
        return jTApellidos.getText();
    }

    public String getjTDireccion() {
        return jTDireccion.getText();
    }

    public String getjTNombres() {
        return jTNombres.getText();
    }

    public String getjTObservaciones() {
        return jTObservaciones.getText();
    }

    public String getjTTelefono() {
        return jTTelefono.getText();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTCedula = new javax.swing.JTextField();
        jTNombres = new javax.swing.JTextField();
        jTApellidos = new javax.swing.JTextField();
        jTTelefono = new javax.swing.JTextField();
        jTCorreo = new javax.swing.JTextField();
        jTDireccion = new javax.swing.JTextField();
        jTObservaciones = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jContraseña = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cedula");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 14, 75, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombres");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 45, 75, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Apellidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 76, 75, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 117, 75, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Correo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 155, 75, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 193, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Dirección");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 231, 75, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Observaciones:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        getContentPane().add(jTCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 11, 145, -1));
        getContentPane().add(jTNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 42, 145, -1));
        getContentPane().add(jTApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 73, 145, -1));
        getContentPane().add(jTTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 114, 145, -1));
        getContentPane().add(jTCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 152, 145, -1));
        getContentPane().add(jTDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 228, 145, -1));
        getContentPane().add(jTObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 266, 145, -1));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 310, -1, -1));

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 310, -1, -1));
        getContentPane().add(jContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 145, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoR.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public boolean isPulsador() {
        return pulsador;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.pulsador = false;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Mesero mesero = new Mesero(jTCedula.getText(), jTNombres.getText(), jTApellidos.getText(),
                jTTelefono.getText(), jTCorreo.getText(), jContraseña.getText(), 
                jTDireccion.getText(), jTObservaciones.getText());
        CrudMesero meseroCrud = new CrudMesero(mesero);
        int i = meseroCrud.insertar();
        this.pulsador = true;
        if(i == 1)
        {
            JOptionPane.showMessageDialog(this, "Mesero Agregado");
        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPasswordField jContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTApellidos;
    private javax.swing.JTextField jTCedula;
    private javax.swing.JTextField jTCorreo;
    private javax.swing.JTextField jTDireccion;
    private javax.swing.JTextField jTNombres;
    private javax.swing.JTextField jTObservaciones;
    private javax.swing.JTextField jTTelefono;
    // End of variables declaration//GEN-END:variables
}
