/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoGUI;

import java.util.ArrayList;
import javax.swing.JTextField;
import proyectomesas.Tipo;

/**
 *
 * @author Hector
 */
public class VentanaAgregar extends javax.swing.JDialog {
    
    ArrayList<Tipo> tipos;
    boolean pulsador;
    /**
     * Creates new form VentanaAgregar
     */
    public VentanaAgregar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.pulsador=false;
        this.setLayout(null);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTPrecio = new javax.swing.JTextField();
        jCTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 46, 71, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Precio:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 77, -1, -1));
        getContentPane().add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 48, 168, -1));
        getContentPane().add(jTPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 77, 168, -1));

        getContentPane().add(jCTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 129, 168, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tipo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 132, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 197, -1, -1));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 197, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Descripcion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 103, -1, -1));
        getContentPane().add(jTDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 103, 168, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 18, -1, -1));
        getContentPane().add(jTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 15, 166, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoR.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        pulsador=true;
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        pulsador=false;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public boolean isPulsador() {
        return pulsador;
    }

    public void setjTDescripcion(String descripcion)
    {
        this.jTDescripcion.setText(descripcion);
    }

    public void setjTNombre(String nombre)
    {
        this.jTNombre.setText(nombre);
    }
    
     public void setjId(String id)
    {
        this.jTID.setText(id);
    }


    public void setjTPrecio(String precio)
    {
        this.jTPrecio.setText(precio);
    }

    public String getjTDescripcion()
    {
        return jTDescripcion.getText();
    }

    public String getjTNombre() 
    {
        return jTNombre.getText();
    }
    
    public String getjTId() 
    {
        return jTID.getText();
    }

    public String getjTPrecio() 
    {
        return jTPrecio.getText();
    }
    
    public void SetTipo(ArrayList<Tipo> tipos)
    {
        this.tipos=tipos;
        for (int i = 0; i < tipos.size(); i++)
        {
            this.jCTipo.addItem(tipos.get(i).getNombre());
        }
    }
    
    public String buscarSeleccion()
    {
        String seleccion = jCTipo.getSelectedItem().toString();
        for (int i = 0; i < tipos.size(); i++) 
        {
            if (seleccion.equals(tipos.get(i).getNombre()))
            {
                return tipos.get(i).getId();
            }
        }
        return null;
    }
    
    public void iniciar()
    {
        initComponents();
    }
    
    public void ocultarTipo()
    {
        this.jCTipo.setEnabled(false);
    }
    
    public void ocultarId()
    {
        this.jTID.setEditable(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> jCTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTDescripcion;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTPrecio;
    // End of variables declaration//GEN-END:variables
}
